spring.application.name=spring_web_tut_1
spring.datasource.url=jdbc:h2:mem:ayaan
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
