spring.application.name=expenseTrackerBasic

spring.datasource.url = jdbc:mysql://localhost:3306/expensetracker
spring.datasource.username = root
spring.datasource.password = root
server.port=8081


# Show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Dialect (often auto-detected, but can set manually)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
